Solar cooling example
oemof-heat/solar_models pull request #1
Opened 2020-09-16 14:09 UTC by FranziPl

This is the example of the solar cooling system. Please have a look.

2020-09-23 13:49 UTC, FranziPl commented
Thanks @jakob-wo , I changed your suggestions.

2020-09-28 15:12 UTC, c-moeller requested changes
Thank you @FranziPl Looks really good.
I've only made some minimal style comments.

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_model.py
> +# import oemof plots
```suggestion
# Import oemof plots
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_model.py
> +    # define the used directories
```suggestion
    # Define the used directories
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_model.py
> +    # storages
```suggestion
    # Storages
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +System C: concrete example: Plot ocooling process with a solar collector
```suggestion
System C: concrete example: Plot of cooling process with a solar collector
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +# import oemof plots
```suggestion
# Import oemof plots
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +    # define the used directories
```suggestion
    # Define the used directories
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +    # sequences:
```suggestion
    # Sequences:
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +    # scalars
```suggestion
    # Scalars
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/electric_results_processing.py
> +    # storage costs must be subtract for reference scenario or added
```suggestion
    # Storage costs must be subtract for reference scenario or added
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +This App will model a cooling system for Oman. An earlier Version calculated
```suggestion
This oemof application models a cooling system for Oman. An earlier version calculated
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +the results of 'Provision of cooling in Oman - a linear optimisation problem
```suggestion
the results of the 'Provision of cooling in Oman - a linear optimisation problem
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +with special consideration of different storage options' IRES 2019
```suggestion
with special consideration of different storage options' of the IRES 2019.
```

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +This App will model a cooling system for Oman. An earlier Version calculated
for a campus building in Oman?

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +the results of 'Provision of cooling in Oman - a linear optimisation problem
Do you like to add a link to the paper?

2020-09-28 15:12 UTC, c-moeller commented on solar_cooling/src/main.py
> +This version is adapted for oemof 0.4 and uses the solar_thermal_collector from
```suggestion
This version is adapted for oemof v0.4 and uses the solar_thermal_collector from
```

2020-09-29 06:56 UTC, FranziPl commented
Thanks @c-moeller . I followed all suggestions.

2020-09-29 06:56 UTC, merged